### ISSUE TITLE
下面这个什么异常？这个真的在你们生产上跑着？

### ISSUE THREAD

**Issue by littleyang** [siaorg/sia-task#32]
2019-05-30 17:48:09.804  INFO 217792 --- [Zookeeper-TreeCacheListener-2] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 60 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2019-05-30 17:48:09.804  INFO 217792 --- [Zookeeper-TreeCacheListener-2] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2019-05-30 17:48:09.805  INFO 217792 --- [Zookeeper-TreeCacheListener-2] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.0
2019-05-30 17:48:09.807 ERROR 217792 --- [Zookeeper-TreeCacheListener-2] o.a.c.framework.recipes.cache.TreeCache  :

java.lang.NullPointerException: null
	at com.sia.scheduler.service.common.CommonService.runJob(CommonService.java:325)
	at com.sia.scheduler.zk.monitor.JobMonitor.acquireJob(JobMonitor.java:289)
	at com.sia.scheduler.zk.monitor.JobMonitor.access$200(JobMonitor.java:60)
	at com.sia.scheduler.zk.monitor.JobMonitor$1.process(JobMonitor.java:372)
	at com.sia.core.curator.CuratorClient$4.childEvent(CuratorClient.java:562)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:749)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:743)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by TeddiWolf** [comment]
欢迎来参观

**Comment by TeddiWolf** [comment]
你在SIA-TASK开源群里不，我们沟通下你遇到的异常怎么产生的。
