### ISSUE TITLE
执行函数报错

### ISSUE THREAD

**Issue by kenneth-bro** [siaorg/sia-task#45]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'set @fail := 0;
        select  DATE_FORMAT(last_time,'%Y-%m-%d %H:%i:%s') as ti' at line 2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by Li-JH** [comment]
可以提供一下mysql版本和报错详细信息吗，看错误提示是语法错误，或者也可以将sql语句放到mysql可视化工具中运行下看看是哪个地方语法错误。

**Comment by kenneth-bro** [comment]
报错的问题是 xml里面的。

set @success := 0;
        set @fail := 0;
        select  DATE_FORMAT(last_time,'%Y-%m-%d %H:%i:%s') as times,
        max(@success := @success + job_finished_count) as successJobTotal,
        max(@fail := @fail + job_exception_count) as failJobTotal
        from
        (select
        job_exception_count, job_finished_count, last_time
        from skyworld_portal_stat
        where last_time >= str_to_date(#{startTime,jdbcType=VARCHAR},'%Y-%m-%d %H:%i:%s')
            and last_time &lt;= str_to_date(#{endTime,jdbcType=VARCHAR},'%Y-%m-%d %H:%i:%s')
        <if test="scheduler != null and scheduler != '' ">
            and scheduler = #{scheduler,jdbcType=VARCHAR}
        </if>
        order by last_time) t
        group by last_time

这种语句 @Li-JH

**Comment by Li-JH** [comment]
提供一下你的mysql版本号和日志报错的信息，就是你最开始贴出来的报错信息，把整个报错信息都提供下吧。你在我们的开源群吗，可以在群里交流下。
